name: CI & CD
on: [push]
jobs:
  get-data-from-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json
      - name: Echo package.json
        run: echo ${{ steps.package.outputs.content }}