name: CI & CD
on: [push]
jobs:
  get-data-from-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Reading & printing file content 
      - name: Read package.json
        id: package
        with:
          path: ./package.json
      - name: Echo package.json
        run: echo ${{ steps.package.outputs.content }}