name: CI & CD
on: [push]
jobs:
  get-data-from-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Read package.json
        id: settings
        uses: juliangruber/read-file-action@v1
        with:
          path: ./settings.json
      - name: Echo settings.json
        run: echo ${{ steps.settings.outputs.content }}