name: CI & CD
on: [push]
jobs:
  get-data-from-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Reading & printing file content 
        run: ls -R $HOME
        # run: cat $HOME/.github/workflows/settings.json
